.TH rbuild\-add 1 2014\-05\-13
.SH NAME
.B
rbuild-add
\-
Add resources to the entitlement service

.SH SYNOPSIS
rbuild add <subcommand> [options]
.SH DESCRIPTION
.PP
Subcommands:
     entitlement  Add entitlement to a product
     permission   Add permissions to a product

(Use 'rbuild help add <subcommand>' for help on a subcommand)

.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.TP
.B \-\-customer=CUSTOMER

.TP
.B \-\-product=PRODUCT

.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
