.TH rbuild\-config 1 2014\-05\-13
.SH NAME
.B
rbuild-config
\-
Print the rbuild configuration
.SH SYNOPSIS
rbuild config 
.SH DESCRIPTION
Print the rbuild configuration
.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.TP
.B \-\-ask
(Re)run interactive config questionaire; write all
.TP
.B \-\-conaryrc
Re-write ~/.conaryrc-rbuild
.TP
.B \-\-rmakerc
Re-write ~/.rmakerc-rbuild
.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
