.TH rbuild\-launch 1 2014\-05\-13
.SH NAME
.B
rbuild-launch
\-
Launch/Deploy an image onto a target
.SH SYNOPSIS
rbuild launch <IMAGE> <TARGET>
rbuild deploy <IMAGE> <TARGET>
.SH DESCRIPTION
.PP
Launch/Deploy an image onto a target
.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.TP
.B \-\-no\-launch
Do not launch an image
.TP
.B \-\-no\-watch
Do not wait for job to complete
.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
