.TH rbuild\-delete 1 2014\-05\-13
.SH NAME
.B
rbuild-delete
\-
Delete rbuilder objects
.SH SYNOPSIS
rbuild delete <subcommand> [options]
.SH DESCRIPTION
.PP
Build the various components of a product
.PP
Subcommands:
     images   Delete images
     targets  Delete targets
.PP
(Use 'rbuild help delete <subcommand>' for help on a subcommand)

.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
