.TH rbuild\-rebase 1 2014\-05\-13
.SH NAME
.B
rbuild-rebase
\-
Update product to most recent platform version 
.SH SYNOPSIS
rbuild rebase [label]
.SH DESCRIPTION
.PP
Modifies the version of the upstream platform and platform
definition currently in use.  In normal use, updates to the
latest version of the platform definition and the latest
version of each of the search path elements specified in
the platform definition.  Alternatively, can be used to
change the upstream platform used by providing the label
for the platform definition for the new upstream platform.
After such a change all packages normally must be rebuilt.

.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.TP
.B \-\-interactive
Allow user to choose whether to apply changes
.TP
.B \-\-test
Show what changes would be applied, but do not apply
.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
