.TH rbuild\-create 1 2014\-05\-13
.SH NAME
.B
rbuild-create
\-
Create or add new resources 
.SH SYNOPSIS
rbuild create <subcommand> [options]
.SH DESCRIPTION
.PP
Commands for creating projects, branches, and other objects 
.PP
Subcommands:
     project   Create a project on SAS App Engine
     imagedef  Create a image defintion on a SAS App Engine
     target    Create a target on a SAS App Engine
     branch    Create a branch within an existing project
.PP
(Use 'rbuild help create <subcommand>' for help on a subcommand)

.SH OPTIONS
.TP
.B \-\-config='KEY
VALUE'
.TP
.B \-\-config\-file=PATH
Read PATH config file
.TP
.B \-\-quiet
Quiet operation, intended for scripting
.TP
.B \-\-skip\-default\-config

.TP
.B \-\-stage=STAGE
Specify the stage to use
.TP
.B \-\-verbose
Display more detailed information where available
.TP
.B \-\-branch=BRANCH

.TP
.B \-\-description=DESCRIPTION

.TP
.B \-\-descrption=DESCRPTION

.TP
.B \-\-domain\-name=DOMAIN\-NAME

.TP
.B \-\-name=NAME

.TP
.B \-\-namespace=NAMESPACE

.TP
.B \-\-platform=PLATFORM

.TP
.B \-\-project=PROJECT

.TP
.B \-\-short\-name=SHORT\-NAME

.SH SEEALSO
 rbuild help <subcommand> 
.SH BUGS
 file issues or bugs
.UR
https://opensource.sas.com/its
 
.SH AUTHORS
.B
 rbuild
was written by SAS
.UR
http://www.sas.com/
.
.SH COPYRIGHT
 Copyright (c)
.B
SAS Institute Inc.
 
