#!/bin/sh
if [ -x reports ]; then
   rm -rf reports;
fi
mkdir reports
cp init_pylint.py reports
cd reports

if [ -z "$*" ]; then
    files="rbuild $(ls $(realpath $(pwd)/../..)/plugins/*.py)"
else
    files=$@
fi

pylint --init-hook='import sys; sys.path.append("."); import init_pylint' --rcfile='../pylintrc' $files
rc=$?
rm init_pylint*;
for file in `ls`; do
   if [ ! -s $file ]; then
      rm $file;
   fi
done
exit $rc
